### PR TITLE
Update README.md example - Serialize using system library

### PR DESCRIPTION
**Pull request by Arxcis**

### CODE REVIEW

**Comment by Per-Morten** [comment]
The intention of the example was to make it obvious how you could go from the list of events from the ToChromeTracingEvents function to a valid output file. That obviousness goes away when you use language/library-specific serialization.

**Comment by Arxcis** [comment]
> The intention of the example was to make it obvious how you could go from the list of events from the ToChromeTracingEvents function to a valid output file. That obviousness goes away when you use language/library-specific serialization.

I can only speak for myself, but I spent more time looking at the serialization part of the example, than the profiling-part, because it was a non-standard implementation. Replacing the serialization code with a call to a standard library function, allowed me to focus more on the profiling-part of the example, which is arguably the most important part :neutral_face:

**Comment by Per-Morten** [comment]
Right. The purpose of that example wasn't actually the profiling-part, but rather, how do you get the data out so you can inspect it. I would argue that is not clear when you're just calling a standard library function. What if your language doesn't have such a function that works in exactly that manner? Then you need to go and figure out how the C# library version of that function works. 

However, I think that your comment has merit and that I should probably add some example code of the profiling API as well. And also tidy up the main example a bit to make it more clear that you're supposed to do string concatenation in a specific format. I'll update the example to specify that it's a list of strings, and remove the profiling code and put that in its own example.

**Comment by Arxcis** [comment]
Ok. Thank you for responding to my PR. I will close this PR then 👍

**Pull request closed without merging**
